name: Generic CI/CD

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - master

jobs:  
  check-for-tag:
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.tag-checker.outputs.is_tag }}
    steps:
      - id: tag-checker
        name: Check if push is for a tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

  test-tag-check:
    runs-on: ubuntu-latest
    needs: [check-for-tag]
    steps:
      - name: test
        run: echo ${{ needs.check-for-tag.outputs.is_tag }}

  rust_tests:
    name: Rust Testing/CI
    uses: ./.github/workflows/rust.yml
    secrets: inherit

  crates_io:
    name: Crate.io Publishing
    if: ${{ startsWith(github.ref,'refs/tags/v') }}
    needs: [rust_tests]
    uses: ./.github/workflows/crates.io.yml
    secrets: inherit