name: Rust 1.70-1.76  

on: [workflow_call]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        rust-version: ['1.70.0', '1.71.0', '1.72.0', '1.73.0', '1.74.0', '1.75.0', '1.76.0']

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    # Setup Rust toolchain
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
        override: true

    # Cache dependencies
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Version
    - name: Display Cargo version
      run: cargo version

    # Build
    - name: Rust Build(cargo build)
      run: cargo build --verbose

    # Test
    - name: Run Tests(cargo test)
      run: cargo test --verbose
